Prophet/Prophet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('teachings', include('teach.urls', namespace='teach')),
    path('about', include('story.urls', namespace='story')),
    path('videos', include('videos.urls', namespace='videos')),
    path('gallery', include('gallery.urls', namespace='gallery')),
    path('contact', include('contact.urls', namespace='contact')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Prophet/contact/urls.py
from django.urls import path

from . import views

app_name = "contact"


urlpatterns = [
    #Leave as empty string for base url

    #------------ (STORE - URLS) ------------

	path('', views.contact, name="contact"),

]

Prophet/gallery/urls.py
from django.urls import path

from . import views

app_name = "gallery"


urlpatterns = [
    #Leave as empty string for base url

    #------------ (STORE - URLS) ------------

	path('', views.gallery, name="gallery"),

]

Prophet/home/urls.py
from django.urls import path

from . import views

app_name = "home"


urlpatterns = [
    #Leave as empty string for base url

    #------------ (STORE - URLS) ------------

	path('', views.home, name="home"),

]

Prophet/story/urls.py
from django.urls import path

from . import views

app_name = "story"


urlpatterns = [
    #Leave as empty string for base url

    #------------ (STORE - URLS) ------------

	path('', views.story, name="story"),

]

Prophet/teach/urls.py
from django.urls import path

from . import views

app_name = "teach"


urlpatterns = [
    #Leave as empty string for base url

    #------------ (STORE - URLS) ------------

	path('', views.teach, name="teach"),
	path('scroll', views.scroll, name="scroll"),

]

Prophet/videos/urls.py
from django.urls import path

from . import views

app_name = "videos"


urlpatterns = [
    #Leave as empty string for base url

    #------------ (STORE - URLS) ------------

	path('', views.videos, name="videos"),

]

Prophet/contact/models.py
from django.db import models

# Create your models here.

Prophet/contact/views.py
from django.shortcuts import render

# Create your views here.
def contact(request):
	return render(request, 'contact.html', {})

Prophet/gallery/views.py
from django.shortcuts import render

# Create your views here.
def gallery(request):

    return render (request, 'gallery.html', {})

Prophet/home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):

    return render (request, 'home.html', {})

Prophet/story/views.py
from django.shortcuts import render

# Create your views here.
def story(request):

    return render (request, 'story.html', {})

Prophet/teach/views.py
from django.shortcuts import render

# Create your views here.
def teach(request):

    return render (request, 'teach.html', {})

def scroll(request):

    return render (request, 'scroll.html', {})

Prophet/videos/views.py
from django.shortcuts import render

# Create your views here.
def videos(request):

    return render (request, 'videos.html', {})

Prophet/templates/contact.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
		<meta name="viewport" content="width=device-width, initial-scale=1"> 
    	<title>Prophet Tinashe R. Mugandani - Global Word Ministries International</title>
		<meta name="keywords" content="Prophet Tinashe Mugandani, Global Word Ministries, prophetic teaching, deliverance ministry, spiritual warfare, prayer and fasting, faith messages, revival, Holy Spirit, divine timing, kingdom principles, prophetic declarations, online sermons">
		<meta name="description" content="Prophet Tinashe R. Mugandani of Global Word Ministries International - powerful prophetic teachings, deliverance, and revival. Watch sermons on prayer, faith, divine timing, and spiritual warfare.">
		<meta name="author" content="Mufudzi Christopher" />
		<link rel="shortcut icon" href="{% static 'contact/favicon.ico' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'contact/css/normalize.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'contact/css/demo.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'contact/css/component.css' %}" />
		<script src="{% static 'contact/js/modernizr.custom.js' %}"></script>
	</head>
	<body>
		<div class="container">
			<!-- Top Navigation -->
			<div class="codrops-top clearfix">
				<a class="codrops-icon codrops-icon-prev" href="{% url 'home:home' %}"><span style="color: #fff">#Home</span></a>
			</div>
<header class="codrops-header">
    <h1>Connect With Us <span>We'd love to hear from you</span></h1>    
</header>
<section>
    <form id="theForm" class="simform">
        <div class="simform-inner">
            <ol class="questions">
                <li>
                    <span><label for="q1">Your full name</label></span>
                    <input id="q1" name="name" type="text" required/>
                </li>
                <li>
                    <span><label for="q2">Email address</label></span>
                    <input id="q2" name="email" type="email" required/>
                </li>
                <li>
                    <span><label for="q3">Phone number (optional)</label></span>
                    <input id="q3" name="phone" type="tel"/>
                </li>
                <li>
                    <span><label for="q4">Your location (city/country)</label></span>
                    <input id="q4" name="location" type="text"/>
                </li>
                <li>
                    <span><label for="q5">How can we pray for you?</label></span>
                    <input id="q5" name="prayer_request" type="text"/>
                </li>
                <li>
                    <span><label for="q6">Your message to the ministry</label></span>
                    <input id="q6" name="message" type="text"/>
                </li>
            </ol><!-- /questions -->
            <button class="submit" type="submit">Send Message</button>
            <div class="controls">
                <button class="next"></button>
                <div class="progress"></div>
                <span class="number">
                    <span class="number-current"></span>
                    <span class="number-total"></span>
                </span>
                <span class="error-message"></span>
            </div><!-- / controls -->
        </div><!-- /simform-inner -->
        <span class="final-message">Thank you! We'll be in touch soon.</span>
    </form><!-- /simform -->            
</section>
		</div><!-- /container -->
		<script src="{% static 'contact/js/classie.js' %}"></script>
		<script src="{% static 'contact/js/stepsForm.js' %}"></script>
		<script>
			var theForm = document.getElementById( 'theForm' );
                        //disable form autocomplete
                        theForm.setAttribute( "autocomplete", "off" );

			new stepsForm( theForm, {
				onSubmit : function( form ) {
					// hide form
					classie.addClass( theForm.querySelector( '.simform-inner' ), 'hide' );

					/*
					form.submit()
					or
					AJAX request (maybe show loading indicator while we don't have an answer..)
					*/

					// let's just simulate something...
					var messageEl = theForm.querySelector( '.final-message' );
					messageEl.innerHTML = 'Thank you! We\'ll be in touch.';
					classie.addClass( messageEl, 'show' );
				}
			} );
		</script>
	</body>
</html>

Prophet/templates/gallery.html
{% load static%}
<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
    	<title>Prophet Tinashe R. Mugandani - Global Word Ministries International</title>
		<meta name="keywords" content="Prophet Tinashe Mugandani, Global Word Ministries, prophetic teaching, deliverance ministry, spiritual warfare, prayer and fasting, faith messages, revival, Holy Spirit, divine timing, kingdom principles, prophetic declarations, online sermons">
		<meta name="description" content="Prophet Tinashe R. Mugandani of Global Word Ministries International - powerful prophetic teachings, deliverance, and revival. Watch sermons on prayer, faith, divine timing, and spiritual warfare.">


		<meta name="author" content="Mufudzi Christopher" />
		<link rel="shortcut icon" href="favicon.ico">
		<link rel="stylesheet" href="https://use.typekit.net/nbm2coz.css">
		<link rel="stylesheet" type="text/css" href="{% static 'gallery/css/base.css' %}" />
		<script>document.documentElement.className="js";</script>
	</head>
	<body class="demo-2 loading">
		<main>
			<header class="frame">
				<h1 class="frame__title"><a href="{% url 'home:home' %}">#Home</a> </h1>
			</header>
			<div class="grid grid--rounded">
				
				<div class="grid__item pos-1"><div class="grid__img" style="background-image:url({% static 'gallery/img/img1.jpg)' %}"></div></div>
				<div class="grid__item pos-2"><div class="grid__img" style="background-image: url({% static 'gallery/img/img2.jpg)' %}"></div></div>
				<div class="grid__item pos-3"><div class="grid__img" style="background-image: url({% static 'gallery/img/img3.jpg)' %}"></div></div>
				<div class="grid__item pos-4"><div class="grid__img" style="background-image:url({% static 'gallery/img/img4.jpg)' %}"></div></div>
				<div class="grid__item pos-5"><div class="grid__img" style="background-image: url({% static 'gallery/img/img5.jpg)' %}"></div></div>
				<div class="grid__item pos-6"><div class="grid__img" style="background-image:url({% static 'gallery/img/img6.jpg)' %}"></div></div>
				<div class="grid__item pos-7"><div class="grid__img" style="background-image:url({% static 'gallery/img/img7.jpg)' %}"></div></div>
				<div class="grid__item pos-8"><div class="grid__img" style="background-image:url({% static 'gallery/img/img8.jpg)' %}"></div></div>
				<div class="grid__item pos-9"><div class="grid__img" style="background-image:url({% static 'gallery/img/img9.jpg)' %}"></div></div>
				<div class="grid__item pos-10"><div class="grid__img" style="background-image: url({% static 'gallery/img/img10.jpg)' %}"></div></div>
				<div class="grid__item pos-11"><div class="grid__img" style="background-image:url({% static 'gallery/img/img11.jpg)' %}"></div></div>
				<div class="grid__item pos-12"><div class="grid__img" style="background-image: url({% static 'gallery/img/img12.jpg)' %}"></div></div>
				<div class="grid__item pos-13"><div class="grid__img" style="background-image:url({% static 'gallery/img/img13.jpg)' %}"></div></div>
				<div class="grid__item pos-14"><div class="grid__img" style="background-image:url({% static 'gallery/img/img1.jpg)' %}"></div></div>
				<div class="grid__item pos-15"><div class="grid__img" style="background-image: url({% static 'gallery/img/img2.jpg)' %}"></div></div>
				<div class="grid__item pos-16"><div class="grid__img" style="background-image: url({% static 'gallery/img/img3.jpg)' %}"></div></div>
				<div class="grid__item pos-4"><div class="grid__img" style="background-image:url({% static 'gallery/img/img4.jpg)' %}"></div></div>
				<div class="grid__item pos-5"><div class="grid__img" style="background-image: url({% static 'gallery/img/img5.jpg)' %}"></div></div>
				<div class="grid__item pos-6"><div class="grid__img" style="background-image:url({% static 'gallery/img/img6.jpg)' %}"></div></div>
				<div class="grid__item pos-7"><div class="grid__img" style="background-image:url({% static 'gallery/img/img7.jpg)' %}"></div></div>
				<div class="grid__item pos-8"><div class="grid__img" style="background-image:url({% static 'gallery/img/img8.jpg)' %}"></div></div>
				<div class="grid__item pos-9"><div class="grid__img" style="background-image:url({% static 'gallery/img/img9.jpg)' %}"></div></div>
				<div class="grid__item pos-10"><div class="grid__img" style="background-image: url({% static 'gallery/img/img10.jpg)' %}"></div></div>
				<div class="grid__item pos-11"><div class="grid__img" style="background-image:url({% static 'gallery/img/img11.jpg)' %}"></div></div>
				<div class="grid__item pos-12"><div class="grid__img" style="background-image: url({% static 'gallery/img/img12.jpg)' %}"></div></div>
				<div class="grid__item pos-13"><div class="grid__img" style="background-image:url({% static 'gallery/img/img13.jpg)' %}"></div></div>
			</div>
		</main>
		<div class="fullscreen fullscreen--rounded"></div>
		<script src="{% static 'gallery/js/imagesloaded.pkgd.min.js' %}"></script>
		<script src="{% static 'gallery/js/gsap.min.js' %}"></script>
		<script src="{% static 'gallery/js/Flip.min.js' %}"></script>
		<script type="module" src="{% static 'gallery/js/demo2/index.js' %}"></script>
	</body>
</html>

Prophet/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="no-js">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
    	<title>Prophet Tinashe R. Mugandani - Global Word Ministries International</title>
		<meta name="keywords" content="Prophet Tinashe Mugandani, Global Word Ministries, prophetic teaching, deliverance ministry, spiritual warfare, prayer and fasting, faith messages, revival, Holy Spirit, divine timing, kingdom principles, prophetic declarations, online sermons">
		<meta name="description" content="Prophet Tinashe R. Mugandani of Global Word Ministries International - powerful prophetic teachings, deliverance, and revival. Watch sermons on prayer, faith, divine timing, and spiritual warfare.">


		<meta name="author" content="Mufudzi Christopher" />
		<link rel="shortcut icon" href="favicon.ico">
		<link href="https://fonts.googleapis.com/css?family=Cormorant+Garamond" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="{% static 'home/css/normalize.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'home/css/demo.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'home/css/demo-entry.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'home/pater/pater.css' %}" />
		<script>document.documentElement.className = 'js';</script>
	</head>
	<body class="demo-grid loading">
		<svg class="hidden">
			<symbol id="icon-arrow" viewBox="0 0 24 24">
				<title>arrow</title>
				<polygon points="6.3,12.8 20.9,12.8 20.9,11.2 6.3,11.2 10.2,7.2 9,6 3.1,12 9,18 10.2,16.8 "/>
			</symbol>
			<symbol id="icon-drop" viewBox="0 0 24 24">
				<title>drop</title>
				<path d="M12,21c-3.6,0-6.6-3-6.6-6.6C5.4,11,10.8,4,11.4,3.2C11.6,3.1,11.8,3,12,3s0.4,0.1,0.6,0.3c0.6,0.8,6.1,7.8,6.1,11.2C18.6,18.1,15.6,21,12,21zM12,4.8c-1.8,2.4-5.2,7.4-5.2,9.6c0,2.9,2.3,5.2,5.2,5.2s5.2-2.3,5.2-5.2C17.2,12.2,13.8,7.3,12,4.8z"/><path d="M12,18.2c-0.4,0-0.7-0.3-0.7-0.7s0.3-0.7,0.7-0.7c1.3,0,2.4-1.1,2.4-2.4c0-0.4,0.3-0.7,0.7-0.7c0.4,0,0.7,0.3,0.7,0.7C15.8,16.5,14.1,18.2,12,18.2z"/>
			</symbol>
		</svg>
		<main>
			<div class="message">Oops! It looks like this website is best suited for desktop.</div>
			<div class="frame">
				<!-- <nav class="demos">
					<a class="demo" href="index.html">Demo 1</a>
					<a class="demo" href="gallery.html">Demo 2</a>
					<a class="demo demo--current" href="entry.html">Demo 3</a>
					<a class="demo" href="grid.html">Demo 4</a>
				</nav> -->
				<h3 class="frame__title">Global Word Ministries -  <mark>Prophet T.R Mugandani</mark></h3>
				<!-- <a class="pater" href="http://go.hackingui.com/NomNomcodrops2507171" onClick="recordOutboundLink(this, 'Outbound Links', 'NomNomcodrops250717');return false;">
					<div class="pater__img pieces" style="background-image: url(img/Sponsor.png)" data-image-alt="img/Sponsor.png"></div>
					<h3 class="pater__title">Data-driven designers use <strong>NomNom</strong> to learn from customers faster</h3>
					<p class="pater__description">The easiest way to search, organize and share all your customer feedback and user research in one place. <strong>NomNom is data-driven design made easy. &rarr;</strong></p>
				</a> -->
			</div>
			<div class="content">
				<nav class="page-nav">
					<a class="page-nav__item" href="{% url 'story:story' %}">About</a>
					<a class="page-nav__item" href="{% url 'teach:teach' %}">Teachings</a>
					<a class="page-nav__item" href="{% url 'videos:videos' %}">Videos</a>
					<a class="page-nav__item" href="{% url 'contact:contact' %}">Contact</a>
					<a class="page-nav__item page-nav__item--close" href="#">Back</a>
				</nav>
				<div class="pieces" style="background-image: url({% static 'home/img/tinashe.jpeg' %})"></div>
				<h2 class="content__title">Explore</h2>
			</div>
		</main>
		<script src="{% static 'home/js/imagesloaded.pkgd.min.js' %}"></script>
		<script src="{% static 'home/js/anime.min.js' %}"></script>
		<script src="{% static 'home/js/main.js' %}"></script>
		<script>
		{
			imagesLoaded(document.body, { background: true }, () => document.body.classList.remove('loading'));

			const piecesEl = document.querySelector('.content .pieces');
			const piecesObj = new Pieces(piecesEl, {
				 pieces: {rows: 14, columns: 12}
			});
			const menuEl = document.querySelector('.page-nav');
			const optionsCtrl = document.querySelector('.content__title');
			const closeOptionsCtrl = menuEl.querySelector('a.page-nav__item--close');

			const showOptions = () => {
				menuEl.classList.add('page-nav--open');

				piecesObj.animate({
					duration: 3000,
					delay: (t,i) => {
						const elBounds = piecesEl.getBoundingClientRect();
						const x1 = elBounds.left + elBounds.width/2;
						const y1 = elBounds.top + elBounds.height/2;
						const tBounds = t.getBoundingClientRect();
						const x2 = tBounds.left + tBounds.width/2;
						const y2 = tBounds.top + tBounds.height/2;
						const dist = Math.sqrt(Math.pow(x2-x1,2) + Math.pow(y2-y1,2));
						const maxDist = Math.sqrt(Math.pow(elBounds.left-x1,2) + Math.pow(elBounds.top-y1,2));
						const maxDelay = 300;

						t.dataset.centerx = x2;
						t.dataset.centery = y2;

						return -1*maxDelay/maxDist*dist + maxDelay;
					},
					easing: [0.1,1,0,1],
					translateX: (t,i) => { 
						return t.dataset.column < piecesObj.getTotalColumns()/2 ? anime.random(-400,0) : anime.random(0,400);
					},
					translateY: (t,i) => { 
						return t.dataset.row < piecesObj.getTotalRows()/2 ? anime.random(-400,0) : anime.random(0,400);
					},
					opacity: 0.2
				});
				
				anime.remove(optionsCtrl);
				anime({
					targets: optionsCtrl,
					duration: 700,
					easing: 'easeOutExpo',
					scale: 1.2,
					opacity: 0
				});

				anime.remove(menuEl);
				anime({
					targets: menuEl,
					duration: 700,
					delay: 150,
					easing: 'easeOutExpo',
					scale: [0,1],
					opacity: 1
				});
			};

			const hideOptions = (ev) => {
				ev.preventDefault();
				menuEl.classList.remove('page-nav--open');

				piecesObj.animate({
					duration: 600,
					delay: (t,i) => {
						const elBounds = piecesEl.getBoundingClientRect();
						const x1 = elBounds.left + elBounds.width/2;
						const y1 = elBounds.top + elBounds.height/2;
						const x2 = t.dataset.centerx;
						const y2 = t.dataset.centery;
						const dist = Math.sqrt(Math.pow(x2-x1,2) + Math.pow(y2-y1,2));
						const maxDist = Math.sqrt(Math.pow(elBounds.left-x1,2) + Math.pow(elBounds.top-y1,2));
						const maxDelay = 800;

						return maxDelay/maxDist*dist;
					},
					easing: [0.1,1,0,1],
					translateX: 0,
					translateY: 0,
					opacity: 1
				});
				
				anime.remove(optionsCtrl);
				anime({
					targets: optionsCtrl,
					duration: 700,
					delay: 200,
					easing: 'easeOutQuint',
					scale: [1.1,1],
					opacity: 1
				});

				anime.remove(menuEl);
				anime({
					targets: menuEl,
					duration: 700,
					easing: 'easeOutQuint',
					scale: 0.8,
					opacity: 0
				});
			};

			optionsCtrl.addEventListener('click', showOptions);
			closeOptionsCtrl.addEventListener('click', hideOptions);
		}
		</script>
		<script src="pater/pater.js"></script>
	</body>
</html>

Prophet/templates/scroll.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="no-js loading">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
    	<title>Prophet Tinashe R. Mugandani - Global Word Ministries International</title>
		<meta name="keywords" content="Prophet Tinashe Mugandani, Global Word Ministries, prophetic teaching, deliverance ministry, spiritual warfare, prayer and fasting, faith messages, revival, Holy Spirit, divine timing, kingdom principles, prophetic declarations, online sermons">
		<meta name="description" content="Prophet Tinashe R. Mugandani of Global Word Ministries International - powerful prophetic teachings, deliverance, and revival. Watch sermons on prayer, faith, divine timing, and spiritual warfare.">


		<meta name="author" content="Mufudzi Christopher" />
		<link rel="shortcut icon" href="favicon.ico">
		<link rel="stylesheet" href="https://use.typekit.net/lnu1fpi.css">
		<link rel="stylesheet" type="text/css" href="{% static 'scroll/css/base.css' %}" />
    	<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js"></script>
		<script>document.documentElement.className="js";</script>
	</head>
	<body class="demo-1">
		<main>
			<header class="frame frame--header type-small">
				<a class="frame__back" href="{% url 'home:home' %}">#Home</a>
				<a class="frame__archive" href="{% url 'teach:teach' %}">All Teachings</a>
				
			</header>
			<section class="intro">
				<div class="intro__heading">

					<p class="type-small">Howdy, cowboy! Before you go scrollin', simmer down and savor the ride. Yeehaw, but easy now!</p>
				</div>
			</section>
			<section class="content">
				<span class="content__number type-small">1</span>
				<div class="blur-text blur-text--1" data-effect-1>
			      	Public opinion is the aggregate result of individual opinions—now uniform, now conflicting—of the men and women who make up society or any group of society. In order to understand public opinion, one must go back to the individual who makes up the group.
			    </div>
		   	</section>
		   	<section class="content">
		   		<span class="content__number type-small">2</span>
				<div class="blur-text blur-text--2" data-effect-2>
			       The mental equipment of the average individual consists of a mass of judgments on most of the subjects which touch his daily physical or mental life.
			    </div>
		   	</section>
		   	<section class="content">
		   		<span class="content__number type-small">3</span>
				<div class="blur-text blur-text--3" data-effect-3>
					These judgments are the tools of his daily being and yet they are his judgments, not on a basis of research and logical deduction, but for the most part dogmatic expressions accepted on the authority of his parents, his teachers, his church, and of his social, his economic and other leaders.
			    </div>
		   	</section>
		   	<section class="content">
		   		<span class="content__number type-small">4</span>
				<div class="blur-text blur-text--4" data-effect-4>
			    	In tracing the interaction of institution upon public and public upon institution, one finds a circle of obedience and leadership. The press, the school and other leaders of thought are themselves working in a background which they cannot entirely control.
			    </div>
		   	</section>

			{% comment %} <footer class="frame frame--footer type-small">
				<span>Created by <a href="https://x.com/codrops">@codrops</a> 2024</span>
				<span>Text from <a href="https://www.gutenberg.org/ebooks/61364">Crystallizing Public Opinion</a> by <a href="https://en.wikipedia.org/wiki/Edward_Bernays">Edward L. Bernays</a></span>
				<a href="https://tympanus.net/codrops/collective/">Subscribe to our frontend newsletter</a>
			</footer> {% endcomment %}
		</main>
		<!-- JavaScript dependencies -->
		<!-- GSAP library -->
		<script src="{% static 'scroll/js/gsap.min.js' %}"></script>
		<!-- GSAP ScrollTrigger plugin -->
		<script src="{% static 'scroll/js/ScrollTrigger.min.js' %}"></script>

		<!-- SplitType for text manipulation: https://github.com/lukePeavey/SplitType -->
		<script src="{% static 'scroll/js/split-type.min.js' %}"></script>

		<!-- Add (Lenis) smooth scroll -->
		<script src="{% static 'scroll/js/lenis.min.js' %}"></script>
		<script src="{% static 'scroll/js/smoothscroll.js' %}"></script>

		<!-- Scripts for the effect -->
		<script type="module" src="{% static 'scroll/js/index.js' %}"></script>
	</body>
</html>